db:
  image: postgres

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db:db
    - redis:redis

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
